# Generated by Django 4.1.5 on 2023-01-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("codesee_cn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codesee_cn.topic",
                    ),
                ),
            ],
            options={"verbose_name_plural": "entries",},
        ),
    ]
